// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVWBA3cbgDXNqAimrLhUhAmvTKpRFWhU0',
    appId: '1:208741799354:web:da9bbbf9a6542623a2f983',
    messagingSenderId: '208741799354',
    projectId: 'motocare-99e43',
    authDomain: 'motocare-99e43.firebaseapp.com',
    storageBucket: 'motocare-99e43.firebasestorage.app',
    measurementId: 'G-H30DX8SC19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGQXaMuzc45J-8kkwOMQDckiTfnQUGHTw',
    appId: '1:208741799354:android:7689da042682d9d9a2f983',
    messagingSenderId: '208741799354',
    projectId: 'motocare-99e43',
    storageBucket: 'motocare-99e43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbCYSumO3zzeSSHAv-VaEErpZp3pBfl0Q',
    appId: '1:208741799354:ios:3043e08b6c868e6ba2f983',
    messagingSenderId: '208741799354',
    projectId: 'motocare-99e43',
    storageBucket: 'motocare-99e43.firebasestorage.app',
    iosBundleId: 'com.example.motocare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbCYSumO3zzeSSHAv-VaEErpZp3pBfl0Q',
    appId: '1:208741799354:ios:3043e08b6c868e6ba2f983',
    messagingSenderId: '208741799354',
    projectId: 'motocare-99e43',
    storageBucket: 'motocare-99e43.firebasestorage.app',
    iosBundleId: 'com.example.motocare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVWBA3cbgDXNqAimrLhUhAmvTKpRFWhU0',
    appId: '1:208741799354:web:b5171356d0bd2207a2f983',
    messagingSenderId: '208741799354',
    projectId: 'motocare-99e43',
    authDomain: 'motocare-99e43.firebaseapp.com',
    storageBucket: 'motocare-99e43.firebasestorage.app',
    measurementId: 'G-VKVQ6RFZ2R',
  );
}
